// auto-generated by circomkit
pragma circom 2.1.2;

include "../withdrawL1.circom";

component main {public[withdrawnValue, stateRoot, stateTreeDepth, ASPRoot, ASPTreeDepth, context, bridgedValue]} = WithdrawL1(32);
